apiVersion: v1
kind: ServiceAccount
metadata:
  name: sqs-eventsource-sa
  namespace: argo-events
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::980794397912:role/iris-mlops-prod-argo-events
---
apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata: {name: dataset-sqs, namespace: argo-events}
spec:
  eventBusName: default
  template:
    serviceAccountName: sqs-eventsource-sa
  sqs:
    dataset:
      jsonBody: true
      region: ap-southeast-1
      queue: iris-mlops-prod-dataset-events
      waitTimeSeconds: 20
