apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: model-release-publisher-github-app
  namespace: argo
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-secrets-manager
  target:
    name: model-release-publisher-github-app
    creationPolicy: Owner
  data:
    - secretKey: client_id
      remoteRef:
        key: REPLACE_MODEL_RELEASE_PUBLISHER_GITHUB_APP_SECRET_ARN
        property: client_id
    - secretKey: private_key
      remoteRef:
        key: REPLACE_MODEL_RELEASE_PUBLISHER_GITHUB_APP_SECRET_ARN
        property: private_key
