apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: model-release-publisher-github-app
  namespace: argo
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-secrets-manager
  target:
    name: model-release-publisher-github-app
    creationPolicy: Owner
  data:
    - secretKey: client_id
      remoteRef:
        key: arn:aws:secretsmanager:ap-southeast-1:980794397912:secret:iris-mlops-prod/github-app/model-release-publisher-p3t2XI
        property: client_id
    - secretKey: private_key
      remoteRef:
        key: arn:aws:secretsmanager:ap-southeast-1:980794397912:secret:iris-mlops-prod/github-app/model-release-publisher-p3t2XI
        property: private_key
