apiVersion: v1
kind: Namespace
metadata:
  name: argo
  annotations:
    argocd.argoproj.io/sync-options: Prune=false
---
apiVersion: v1
kind: Namespace
metadata:
  name: argo-events
  annotations:
    argocd.argoproj.io/sync-options: Prune=false
---
apiVersion: v1
kind: Namespace
metadata:
  name: external-dns
  annotations:
    argocd.argoproj.io/sync-options: Prune=false
---
apiVersion: v1
kind: Namespace
metadata:
  name: external-secrets
  annotations:
    argocd.argoproj.io/sync-options: Prune=false
---
apiVersion: v1
kind: Namespace
metadata:
  name: kserve
  annotations:
    argocd.argoproj.io/sync-options: Prune=false
---
apiVersion: v1
kind: Namespace
metadata:
  name: mlops
  annotations:
    argocd.argoproj.io/sync-options: Prune=false
---
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
  annotations:
    argocd.argoproj.io/sync-options: Prune=false
