apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - project.yaml
  - platform-argo-workflows.yaml
  - platform-argo-events.yaml
  - platform-external-secrets.yaml
  - platform-monitoring.yaml
  - platform-aws-load-balancer-controller.yaml
  - platform-external-dns.yaml
  - platform-knative-crds.yaml
  - platform-knative.yaml
  - platform-kserve-crd.yaml
  - platform-kserve.yaml
  - workload-model-registry.yaml
  - workload-data-pipeline.yaml
  - workload-inference.yaml
