apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-argo-workflows
  namespace: argocd
  annotations: {argocd.argoproj.io/sync-wave: "-40"}
spec:
  project: iris-production
  source:
    repoURL: https://argoproj.github.io/argo-helm
    chart: argo-workflows
    targetRevision: 2.0.2
    helm:
      releaseName: argo-workflows
      valuesObject:
        controller:
          workflowNamespaces: [argo]
          metricsConfig:
            enabled: true
          serviceMonitor:
            enabled: true
            additionalLabels: {release: monitoring}
        server:
          authModes: [server]
  destination: {server: "https://kubernetes.default.svc", namespace: argo}
  syncPolicy:
    automated: {prune: true, selfHeal: true}
    syncOptions: [ServerSideApply=true]
    retry: {limit: 10}
