apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-aws-load-balancer-controller
  namespace: argocd
  annotations: {argocd.argoproj.io/sync-wave: "-37"}
spec:
  project: iris-production
  source:
    repoURL: https://aws.github.io/eks-charts
    chart: aws-load-balancer-controller
    targetRevision: 1.14.0
    helm:
      releaseName: aws-load-balancer-controller
      valuesObject:
        clusterName: iris-mlops-prod
        region: ap-southeast-1
        vpcId: vpc-0fede7eff9e4e881a
        replicaCount: 2
        serviceAccount:
          create: true
          name: aws-load-balancer-controller
          annotations:
            eks.amazonaws.com/role-arn: arn:aws:iam::980794397912:role/iris-mlops-prod-aws-load-balancer-controller
            eks.amazonaws.com/sts-regional-endpoints: "true"
  destination: {server: "https://kubernetes.default.svc", namespace: kube-system}
  syncPolicy:
    automated: {prune: true, selfHeal: true}
    syncOptions: [ServerSideApply=true]
    retry: {limit: 10}
