apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-kserve
  namespace: argocd
  annotations: {argocd.argoproj.io/sync-wave: "-25"}
spec:
  project: iris-production
  source:
    repoURL: ghcr.io/kserve/charts
    chart: kserve-resources
    targetRevision: v0.19.0
    helm:
      valuesObject:
        kserve:
          controller:
            deploymentMode: Knative
            gateway:
              disableIstioVirtualHost: true
              localGateway:
                gatewayService: kourier-internal.knative-serving.svc.cluster.local
                knativeGatewayService: kourier-internal.knative-serving.svc.cluster.local
  destination: {server: "https://kubernetes.default.svc", namespace: kserve}
  syncPolicy:
    automated: {prune: true, selfHeal: true}
    syncOptions: [ServerSideApply=true]
    retry: {limit: 10}
