apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-external-secrets
  namespace: argocd
  annotations: {argocd.argoproj.io/sync-wave: "-40"}
spec:
  project: iris-production
  source:
    repoURL: https://charts.external-secrets.io
    chart: external-secrets
    targetRevision: 2.9.0
    helm:
      releaseName: external-secrets
      valuesObject:
        installCRDs: true
        serviceAccount:
          annotations:
            eks.amazonaws.com/role-arn: arn:aws:iam::980794397912:role/iris-mlops-prod-external-secrets
  destination: {server: "https://kubernetes.default.svc", namespace: external-secrets}
  syncPolicy:
    automated: {prune: true, selfHeal: true}
    syncOptions: [ServerSideApply=true]
    retry: {limit: 10}
