apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: iris-production
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-100"
    argocd.argoproj.io/sync-options: Prune=false
spec:
  description: Production Iris MLOps platform
  sourceRepos:
    - https://github.com/chiendz11/iris-gitops.git
    - https://argoproj.github.io/argo-helm
    - https://charts.external-secrets.io
    - https://prometheus-community.github.io/helm-charts
    - https://aws.github.io/eks-charts
    - https://kubernetes-sigs.github.io/external-dns/
    - https://charts.jetstack.io
    - ghcr.io/kserve/charts
  destinations:
    - namespace: "*"
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"
  orphanedResources:
    warn: true
