apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata: {name: mlflow-database, namespace: mlops}
spec:
  refreshInterval: 1h
  secretStoreRef: {kind: ClusterSecretStore, name: aws-secrets-manager}
  target: {name: mlflow-database, creationPolicy: Owner}
  data:
    - secretKey: POSTGRES_USER
      remoteRef: {key: arn:aws:secretsmanager:ap-southeast-1:980794397912:secret:rds!db-bc45b10a-7499-4549-a71e-d91fad73ef23-DBurbM, property: username}
    - secretKey: POSTGRES_PASSWORD
      remoteRef: {key: arn:aws:secretsmanager:ap-southeast-1:980794397912:secret:rds!db-bc45b10a-7499-4549-a71e-d91fad73ef23-DBurbM, property: password}
